more logs

diff --git a/my-cni b/my-cni
--- a/my-cni
+++ b/my-cni
@@ -52,7 +52,7 @@ allocate_ip() {
   
   # Extract first three octets from subnet
   local prefix=$(echo $SUBNET | /bin/cut -d'/' -f1 | /bin/cut -d'.' -f1-3)
-  log "INFO" "${prefix}.${octet4}"
+  log "INFO" "allocated ${prefix}.${octet4} for container $CONTAINER_ID"
   echo "${prefix}.${octet4}"
 }
 
@@ -61,15 +61,32 @@ handle_add() {
 VETH_HOST="veth$(echo $CONTAINER_ID | cut -c1-8)"
 VETH_NETNS=veth_netns
 ip link add ${VETH_HOST} type veth peer name ${VETH_NETNS}
+if [ $? -eq 0 ]; then
+  log "INFO" "created veth pair: $VETH_HOST-$VETH_NETNS"
+else
+  log "ERROR" "could not create veth pair"
+  exit $?
+fi
 
 # put one of the veth interfaces into the new network namespace
 ip link set ${VETH_NETNS} netns ${NETNS}
+if [ $? -eq 0 ]; then
+  log "INFO" "added veth $VETH_NETNS to the namespace $NETNS"
+else
+  log "ERROR" "could not add veth to the namespace"
+  exit $?
+fi
 
 # assign IP to veth interface inside the new network namespace
 IP_VETH_NETNS=$(allocate_ip)
 CIDR_VETH_NETNS=${IP_VETH_NETNS}/32
 ip -n ${NETNS} addr add ${CIDR_VETH_NETNS} dev ${VETH_NETNS}
-log "INFO" "assigned $CIDR_VETH_NETNS to the container $CONTAINER_ID"
+if [ $? -eq 0 ]; then
+  log "INFO" "assigned $CIDR_VETH_NETNS to the container $CONTAINER_ID"
+else
+  log "ERROR" "could not assign $CIDR_VETH_NETNS to the container $CONTAINER_ID"
+  exit $?
+fi
 
  if ! ip link show ${BRIDGE} &>/dev/null; then
    log "INFO"  "Creating bridge ${BRIDGE}"
